### ISSUE TITLE
AI News Writer Successfully Generates Content but Does Not Display It

### ISSUE THREAD

**Issue by uniqueumesh** [AJaySi/AI-Writer#154]
Hello @AJaySi ,

I encountered an issue with the AI News Writer feature. The system successfully generates a news report (as indicated by the success message), but the actual content is not displayed in the UI.

**Steps to Reproduce:**

- Open Alwrity and navigate to AI Writers.
- Select Write News Reports.
- Enter keywords (e.g., Upcoming AI Trends in 2025).
- Select an origin country (e.g., India) and language (e.g., English).
- Click Generate News Report.

**A success message appears:**

- ✅ Successfully generated news report on: Upcoming AI Trends in 2025 🎉
- However, no content is displayed below the success message (it just shows None).

**Expected Behavior:**

- The generated news report should be visible on the screen.

**Actual Behavior:**

- The UI displays a success message but does not show the generated content.

**Debugging Information from CLI Logs:**

I checked the command-line logs, and it confirms that the AI News Writer is successfully fetching and generating content.

This suggests that the backend is working fine, but the frontend might not be rendering the output properly.

**Screenshots for Reference:**

UI Issue (Content Not Displayed):

![Image](https://github.com/user-attachments/assets/c7987218-26fd-48c0-8ffb-8584d6dff416)

CLI Output (Shows Successful Generation):

![Image](https://github.com/user-attachments/assets/d428b01a-ed38-43ff-bc74-39f11dc6a13b)

Could you please look into this? Let me know if you need any additional details.

Thank you! 🙏

**Comment by uniqueumesh** [comment]
The AI News Writer tool on alwrity.com is failing to generate news reports. When attempting to fetch articles from Google News, the system returns a 403 Unauthorized error, preventing the report generation process.

**Environment Details**

- Platform: [Alwrity Web App] (https://www.alwrity.com/ai-news-generator)

Here is the screen short reference:

![Image](https://github.com/user-attachments/assets/09d5ef4b-5b53-4c1e-93cf-5fad1adeb221)

**Comment by AJaySi** [comment]
@uniqueumesh 
Thank you for the details and info. I will look into it and update here.

**Comment by AJaySi** [comment]
@uniqueumesh 
I have fixed it, please rebase to get latest code and try again. 
Request to check if the article is factually correct, I will try to add more better prompts.

Thank you.

**Comment by uniqueumesh** [comment]
@AJaySi 

I appreciate your support. I am still encountering the same issue as I mentioned above.

**Comment by AJaySi** [comment]
@uniqueumesh  
hmmmm, just to confirm, you do have the latest code from github ?

**Comment by AJaySi** [comment]
@uniqueumesh 
I have assigned this to you, let me know if you need any help on this. Thanks.

**Comment by uniqueumesh** [comment]
@AJaySi 

Thank you for assigning this issue to me. I will look into the root cause and update you on my findings.

**Comment by uniqueumesh** [comment]
Hello @AJaySi 

- Today, I separately installed and tested the News Writer locally, and it generated news smoothly.

- I also tested the News Writer within the ALwrity main tool, and it worked fine without any errors.

- I encountered an error when using the News Writer on our webpage app (https://www.alwrity.com/ai-news-generator) 


I have attached a screenshot for reference.


News writer in local host:

![Image](https://github.com/user-attachments/assets/91e69168-21be-479c-aad2-b12b87b3d6a3)

News writer in ALwrity main:

![Image](https://github.com/user-attachments/assets/fc13ccbf-e87d-4408-aba5-095abedcd119)

News write in webpage app

![Image](https://github.com/user-attachments/assets/567357bc-2ddc-4e7b-90e2-3f1dafaa7ece)

**Comment by AJaySi** [comment]
Well, I suspect the API key is at fault in this codebase: https://github.com/AJaySi/alwrity_news_writer
Try with a new key and directly giving it in the code. If that works then we create a .env file and upload that.
Check Error 403 and its meaning::

https://www.google.com/search?q=api+erorr+403&oq=api+erorr+403&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQABgNGIAEMgkIAhAAGA0YgAQyCAgDEAAYFhgeMggIBBAAGBYYHjIICAUQABgWGB4yCAgGEAAYFhgeMggIBxAAGBYYHjIICAgQABgWGB4yCAgJEAAYFhge0gEIMzY5OWoxajeoAgCwAgA&sourceid=chrome&ie=UTF-8

**Comment by uniqueumesh** [comment]
Thank you @AJaySi 

Now AI News writer on ALwrity webpage is generating news articles without any error.

**Comment by AJaySi** [comment]
@uniqueumesh Great Job.
